### ISSUE TITLE
 [Bug] Popping/Clear kb shortcuts don't work

### ISSUE THREAD

**Issue by LandKingdom** [DenialAdams/ripclip#5]
Version: 0.5.0
Description: Popping the stack from the shortcut clears it instead. The clear shortcut does nothing. (Swapping works). All tray icon's menu options work as expected.

Note: I wasn't able to use the trace feature you provided, I'm probably using it wrong.

**Comment by DenialAdams** [comment]
ah, damnit, last minute refactoring gone wrong! I see the problem, testing out the fix

**Comment by DenialAdams** [comment]
Just posted 0.6.0 with the fix landed (6645569db6e27eb5c0ded67ec95c2f2a44ccfe00). Let me know if this fixes it!

**Comment by LandKingdom** [comment]
It does.
