### ISSUE TITLE
[Bug] .conf mayhem

### ISSUE THREAD

**Issue by LandKingdom** [DenialAdams/ripclip#6]
Adding 2 new lines at the end of the conf file stops the program from starting.

my config file: 
`max_stack_size = 100
show_tray_icon = true
pop_keybinding = Control + Alt + C
swap_keybinding = Control + Alt + S
clear_keybinding = Control + Alt + D
prevent_duplicate_push = false

`

Also, can we have the default config file being in the same folder as the executable? Or maybe have it check for a config there first.

**Comment by DenialAdams** [comment]
Fixed the empty line parsing in f2ca1478c2fa8317d7b2a1f2c301946cba40b3b7 (now we allow blank lines  anywhere throughout the config.) I'll include that in the next release (probably with other suggestion) but lmk if you need it earlier.

As for the configuration file in the same folder as the executable, yes that's a good idea. I think I'll take the approach of checking the local directory for a configuration and prioritizing that one; but I want to think on it for a bit.

Thanks again for the bug reports and suggestions :D

**Comment by LandKingdom** [comment]
No I don't need the fix to be released. Also I was wondering why you bumped up MINOR instead of PATCH for the last bugfix: cargo crates use [Semantic Versioning](https://semver.org/).

**Comment by DenialAdams** [comment]
Yes, it should have been a patch release (thought about that this morning.)
But, since this a binary and not a library the versioning is much less
important anyway (imo.)

**Comment by DenialAdams** [comment]
Added a test for this issue in 1c84e63f2276600995c9aeb0c78d2b1b04336c9c
